#!/usr/bin/gawk -f
# --- T2-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
# 
# T2 SDE: misc/tools-source/smartwr.awk
# Copyright (C) 2004 - 2006 The T2 SDE Project
# 
# More information can be found in the files COPYING and README.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- T2-COPYRIGHT-NOTE-END ---

BEGIN {
	speedargidx=0;
	sizeargidx=0;
	isholy=0;
}

ARGIND == 1 {
	holylist[$4] = 1;
}

ARGIND == 2 {
	if ( gsub("^-SPEED", "") == 1 )
		speedarg[speedargidx++] = $0;
	else
	if ( gsub("^-SIZE", "") == 1 )
		sizearg[sizeargidx++] = $0;
	else {
		speedarg[speedargidx++] = $0;
		sizearg[sizeargidx++] = $0;
	}
	if ( holylist[$0] == 1 )
		isholy=1;
}

END {
	if ( isholy )
		for (i=0; i<speedargidx; i++)
			print speedarg[i];
	else
		for (i=0; i<sizeargidx; i++)
			print sizearg[i];
}

