#!/bin/sed
# --- SDE-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
# 
# Filename: etc/download.sed
# Copyright (C) 2006 - 2007 The OpenSDE Project
# Copyright (C) 2005 - 2006 The T2 SDE Project
# 
# More information can be found in the files COPYING and README.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- SDE-COPYRIGHT-NOTE-END ---

# normal user will always find their files on our mirrors, so this will be used only by developers

s,^http://ftp.gnu.org/gnu/,http://ftp.belnet.be/mirror/ftp.gnu.org/gnu/,
s,^http://www.mysql.org/Downloads/,http://www.mirrorservice.org/sites/ftp.mysql.com/Downloads/,

#s,^ftp://ftp.kde.org/pub/kde/,http://ibiblio.org/pub/mirrors/kde/,

# loadbalancer is working weird these days
s,^http://.*dl.\(sourceforge\|sf\).net/,http://heanet.dl.sourceforge.net/,

# PostgreSQL Team does not like us to use their ftp
s,^ftp://ftp.postgresql.org/pub/source/,ftp://ftp.us.postgresql.org/pub/mirrors/postgresql/source/,

# ftp connection blocks once in a while
s,^ftp://ftp.gnupg.org,http://ftp.gnupg.org,
s,^ftp://ftp.kernel.org,http://ftp.kernel.org,

# clip's ftp is a pain
#s,^ftp://ftp.itk.ru/,ftp://www.cis.by/pub/clip/,

# evolt.org doesn't allow direct downloads
s,http://browsers.evolt.org/download.php?,http://www.mirrorservice.org/sites/browsers.evolt.org/browsers,

# apache mirrors
s,^http://dl.apache.org/,http://www.eu.apache.org/,
