#!/bin/sh
# --- SDE-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
# 
# Filename: src/tools-source/fl_wrapper_test.sh
# Copyright (C) 2010 The OpenSDE Project
# 
# More information can be found in the files COPYING and README.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- SDE-COPYRIGHT-NOTE-END ---

echo -n > rlog.txt
echo -n > wlog.txt

if [ "$1" = "gdb" ]; then
	shift
	cat > fltest.gdb <<-EOT
	set env LD_PRELOAD ./fl_wrapper.so
	set env FLWRAPPER_RLOG rlog.txt
	set env FLWRAPPER_WLOG wlog.txt
	EOT

	exec gdb -x fltest.gdb ./fltest
fi

export FLWRAPPER_RLOG=rlog.txt
export FLWRAPPER_WLOG=wlog.txt

LD_PRELOAD=./fl_wrapper.so ./fltest
