#!/bin/sh
#
# --- SDE-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
# 
# Filename: src/tools-source/fl_wrapper_test.sh
# Copyright (C) 2006 The OpenSDE Project
# Copyright (C) 2004 - 2006 The T2 SDE Project
# Copyright (C) 1998 - 2003 Clifford Wolf
# 
# More information can be found in the files COPYING and README.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- SDE-COPYRIGHT-NOTE-END ---

for x in exec{l,v}{,p,e} ; do
touch fltest_$x ; done

bash src/tools-source/fl_wrapper.c.sh > fl_wrapper.c
gcc -O2 -shared -fPIC -Wall -ldl fl_wrapper.c -o fl_wrapper.so

echo -n > rlog.txt
echo -n > wlog.txt

export FLWRAPPER_RLOG=rlog.txt
export FLWRAPPER_WLOG=wlog.txt

gcc src/tools-source/fl_wrapper_test.c -o fltest_bin
LD_PRELOAD=./fl_wrapper.so ./fltest_bin

#rm fltest_* fl_wrapper.so

