.\"     Title: sde-export
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 01/26/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "SDE\-EXPORT" "1" "01/26/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sde\-export \- Export stuff out of the system
.SH "SYNOPSIS"
\fBsde export\fR [\fIDISCRIMINATOR\fR] [\fIOPTIONS\fR] [\fIITEM\fR] filename
.sp
.SH "DESCRIPTION"
Exports part of the sde system specified by item. All information belonging to the specified item will be wrapped up in a single bundle and written to the specified file. This file can be imported (\fBsde import\fR) again later or on a different host elsewhere. This command is ideal for sending information to the opensde mailing list or sharing uncommitted changes with co\-workers.
.sp
.SH "DISCRIMINATORS"
.PP
\fBconfig, cfg\fR
.RS 4
Wraps up the config specified by item and writes it to the specified file. Besides the config information, also information about the host system is included. This is needed to detect difference between the current host and the target system where the exported results will be imported.
.RE
.PP
\fBpackage, pkg\fR
.RS 4
Wraps up the package specified by item and writes it to the specified file. Besides the package content, also the fully qualified package name will be stored. This is needed to be able to recreate the package at the exact same location on import.
.RE
.PP
\fBtarget, tgt\fR
.RS 4
Wraps up the target specified by item and writes it to the specified file.
.RE
.SH "OPTIONS FOR ALL DISCRIMINATORS"
.PP
\fB\-f, \-\-force\fR
.RS 4
Makes it possible to overwrite existing files. Normal processing will abort when the given file already exists.
.RE
.PP
\fB\-q, \-\-quiet\fR
.RS 4
Reduces the verbosity level.
.RE
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Increases the verbosity level.
.RE
.SH "OPTIONS FOR PACKAGE AND TARGET DISCRIMINATORS"
.PP
\fB\-d, \-\-diff\fR
.RS 4
Only wraps up changes to reduce filesize.
.RE
.SH "AUTHOR"
Written by Minto van der Sluis (misl).
.sp
.SH "REPORTING BUGS"
Report bugs to <list@opensde.org>.
.sp
.SH "COPYRIGHT"
Copyright \(co 2007 The OpenSDE project. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.sp
