.\"     Title: sde-help
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 11/26/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "SDE\-HELP" "1" "11/26/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sde\-help \- provides help about the usage of the *sde* wrapper
.SH "SYNOPSIS"
\fBsde help\fR [\fICOMMAND\fR]
.sp
.SH "DESCRIPTION"
Provides help about the commands available for the \fBsde\fR wrapper on the current tree. To see a full list of available commands, issue the \fBsde help\fR without any arguments. To get help on a specific command, use that command as an argument
.sp
.SH "AUTHOR"
Written by Minto van der Sluis (misl).
.sp
.SH "REPORTING BUGS"
Report bugs to <list@opensde.org>.
.sp
.SH "COPYRIGHT"
Copyright \(co 2007 The OpenSDE project. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.sp
