.\"     Title: sde-config
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 07/12/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "SDE\-CONFIG" "1" "07/12/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sde\-config \- configures part of the system
.SH "SYNOPSIS"
\fIsde config\fR [DISCRIMINATOR] [OPTIONS]
.sp
.SH "DISCRIMINATORS"
.PP
config, cfg
.RS 4
TODO (this is the default if none is given)
.RE
.PP
system, sys
.RS 4
Allows to query or modify global sde configuration parameters.
.RE
.SH "OPTIONS FOR \fICONFIG\fR DISCRIMINATOR"
.PP
\-n, \-\-non\-interactive
.RS 4
Reconfigures an existing config without the interactive configuration application.
.RE
.PP
\-c, \-\-cfg name
.RS 4
Defines the name to be used for a given
\fIconfig\fR, the name
\fIdefault\fR
is used if this option is not supplied.
.RE
.PP
\-\-nobashmod
.RS 4
Don't use the bash config helper plugin
.RE
.PP
\-\-profile
.RS 4
Create a config.profile with profiling data
.RE
.PP
\-q, \-\-quiet
.RS 4
Feedback will be reduced to an absolute minimum.
.RE
.PP
\-v, \-\-verbose
.RS 4
Feedback will be augmented with additional information.
.RE
.SH "OPTIONS FOR \fISYSTEM\fR DISCRIMINATOR"
.PP
\-g, \-\-get key
.RS 4
returns the value of a specified
\fIsection.key\fR
.RE
.PP
\-s, \-\-set key=value
.RS 4
sets the value of a specified
\fIsection.key\fR
.RE
.PP
\-\-dump
.RS 4
dumps the relevant content of the
\fIsettings\fR
file for the current sde instance.
.RE
.PP
\-\-path
.RS 4
outputs the full path to the
\fIsettings\fR
file in use.
.RE
.SH "DESCRIPTION"
sde\-config configures the identified part (item) within the sde environment section indicated by the discriminator.
.sp
.SH "SECTIONS AND KEYS ON GLOBAL SDE CONFIGURATION"
.RS 4
\h'-04'\(bu\h'+03'
\fIdownload\fR
.RS 4
\h'-04'\(bu\h'+03'
\fIaltdir\fR
.RE
.RS 4
\h'-04'\(bu\h'+03'
\fIcurl\-opt\fR
.RE
.RS 4
\h'-04'\(bu\h'+03'
\fImirror\fR
(kept unique per version only)
.RE
.RE
