.\"     Title: sde-install
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 07/10/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "SDE\-INSTALL" "1" "07/10/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sde\-install \- install the wrapper
.SH "SYNOPSIS"
\fIsde install\fR
.sp
.SH "DESCRIPTION"
Install the sde wrapper on \fI$HOME/bin\fR which is expected to be on your \fI$PATH\fR.
.sp
