.\"     Title: sde-commit
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 08/10/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "SDE\-COMMIT" "1" "08/10/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sde\-commit \- Commit changes
.SH "SYNOPSIS"
\fIsde commit\fR [DISCRIMINATORS] [OPTIONS] [ITEMS\]
.sp
.SH "DESCRIPTION"
Commits changes to the identified part (item) within the sde environment section indicated by the discriminator. When the user has commit rights to the SCM repository containing the item, using this command will indeed commit the changes. If there are no commit rights to the repository, all changes will be wrapped up in a patch and send to the mailing list.
.sp
.SH "DISCRIMINATORS"
.PP
package, pkg
.RS 4
Commits changes to the specified package(s).
.RE
.PP
repository, repo
.RS 4
Commits all modified pkgs in the specified repository.
.RE
.PP
system, sys
.RS 4
Commits all changes to the sde framework itself. For this discriminator no items should be provided.
.RE
.PP
target, tgt
.RS 4
Commits changes to the specified target(s).
.RE
When no discriminator is specified, package will be used as the default discriminator.
.sp
.SH "OPTIONS"
.PP
\-\-dry\-run, \-d
.RS 4
Gives feedback of what would be done, but does not really commit.
.RE
.PP
\-\-message, \-m
.RS 4
Allows to specify the commit message on the command line. The argument specifies the actual commit message.
.RE
.PP
\-\-file, \-f
.RS 4
Allows long commit message to be read frome file. The argument specifies the file from which to read the message.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.nf
sde ci .
.fi
.RE
