.\"     Title: sde-download
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 01/26/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "SDE\-DOWNLOAD" "1" "01/26/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sde\-download \- Downloads packages
.SH "SYNOPSIS"
\fBsde download\fR [\fIDISCRIMINATOR\fR] [\fIOPTIONS\fR] [\fIITEMS\fR]
.sp
.SH "DESCRIPTION"
sde\-download downloads one or more packages indicated by or belonging to the specified items. Multiple items can be specified.
.sp
.SH "DISCRIMINATORS"
.PP
\fBconfig, cfg\fR
.RS 4
Downloads all selected packages in the specified config (item).
.RE
.PP
\fBpackage, pkg\fR
.RS 4
Downloads single packages specified by item.
.RE
.PP
\fBrepository, repo\fR
.RS 4
Downloads all packages in the repositories specified by item.
.RE
When no discriminitor is given on the command line the current working directory will be used to determine the discriminator. If still no discriminator can be determined, the \fBpackage\fR discriminator will be used.
.sp
.SH "OPTIONS FOR ALL DISCRIMINATORS"
.PP
\fB\-q, \-\-quiet\fR
.RS 4
Reduces the verbosity level.
.RE
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Increases the verbosity level.
.RE
.PP
\fB\-n, \-\-dry\-run\fR
.RS 4
Process normally, but instead of downloading missing files a message will be written to the terminal for every missing file.
.RE
.PP
\fB\-\-timeout none|normal|long\fR
.RS 4
Defines how tolerat to download delay are we. The default value is
\fBnormal\fR. Other values are
\fBnone\fR
for no timeout at all and
\fBlong\fR
for a longer than normal timeout.
.RE
.PP
\fB\-\-check never|download|always\fR
.RS 4
Defines when downloads should be checked against the checksum in package
\fB.desc\fR
files. By default checksums will
\fBalways\fR
checked. Other possible values are
\fBnever\fR
to disable checksum verification and
\fBdownload\fR
to only verify on downloading. In this last case checksums will not be validated when an alternative (\fB\-\-alt\-dir\fR) download location is used.
.RE
.PP
\fB\-\-mirror none|auto|URL\fR
.RS 4
Defines which mirror to use. Whatever is selected here overrides the default stored on the global config settings. Alternatively you can use
\fBnone\fR
for disabling mirroring or
\fBauto\fR
to detect the best mirror for your location.
.RE
.PP
\fB\-\-alt\-dir location\fR
.RS 4
Defines an alternative download location. The OpenSDE downloader will first look for files in this location. When not present download will continue as usual. Also have a look at option
\fB\-\-mode\fR.
.RE
.PP
\fB\-m, \-\-mode hardlink|copy|move\fR
.RS 4
Defines how files from an alternative download location will be handled. By default a
\fBhardlink\fR
to these files will be created. Other options are
\fBcopy\fR
and
\fBmove\fR
to copy/move the file over to the local download repository.
.RE
.SH "OPTIONS FOR PACKAGE AND REPOSITORY DISCRIMINATORS"
.PP
\fB\-e, \-\-extenders configname\fR
.RS 4
Besided downloading files for specified packages, also downloads from packages extending the given packages will be retrieved. However, only extenders activated in the given config will be taken into account.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.nf
sde download .
sde download package \-\-extenders myconfig mypackage
.fi
.RE
.SH "AUTHOR"
Written by Minto van der Sluis (misl).
.sp
.SH "REPORTING BUGS"
Report bugs to <list@opensde.org>.
.sp
.SH "COPYRIGHT"
Copyright \(co 2007 The OpenSDE project. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.sp
