.\"     Title: sde-config
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 11/26/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "SDE\-CONFIG" "1" "11/26/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sde\-config \- configures part of the system
.SH "SYNOPSIS"
\fBsde config\fR [\fIDISCRIMINATOR\fR] [\fIOPTIONS\fR] [\fIITEM\fR]
.sp
.SH "DESCRIPTION"
sde\-config configures part of your sde environment specified by the given discriminator.
.sp
.SH "DISCRIMINATORS"
.PP
\fBconfig, cfg\fR
.RS 4
Configures the config identified by ITEM. If no item specified the config will be named
\fIdefault\fR.
.RE
.PP
\fBsystem, sys\fR
.RS 4
Makes it possible to query or modify global sde configuration parameters. For this discriminator no item should be specified.
.RE
When no discriminator is detected, this command will default to the \fBconfig\fR discriminator.
.sp
.SH "OPTIONS FOR CONFIG DISCRIMINATOR"
.PP
\fB\-n, \-\-non\-interactive\fR
.RS 4
Reconfigures an existing config without the interactive configuration application.
.RE
.PP
\fB\-\-nobashmod\fR
.RS 4
Don't use the bash config helper plugin
.RE
.PP
\fB\-\-profile\fR
.RS 4
Create a config.profile with profiling data
.RE
.PP
\fB\-q, \-\-quiet\fR
.RS 4
Reduces feedback to an absolute minimum. \-v, \-\-verbose: Gives additional feedback.
.RE
.SH "OPTIONS FOR SYSTEM DISCRIMINATOR"
.PP
\fB\-g, \-\-get key\fR
.RS 4
returns the value of a specified
\fIsection.key\fR
.RE
.PP
\fB\-s, \-\-set key=value\fR
.RS 4
sets the value of a specified
\fIsection.key\fR
.RE
.PP
\fB\-\-dump\fR
.RS 4
dumps the relevant content of the
\fIsettings\fR
file for the current sde instance.
.RE
.PP
\fB\-\-path\fR
.RS 4
outputs the full path to the
\fIsettings\fR
file in use.
.RE
.SH "SECTIONS AND KEYS ON GLOBAL SDE CONFIGURATION"
.RS 4
\h'-04'\(bu\h'+03'
\fIdownload\fR
.RE
.RS 4
\h'-04'\(bu\h'+03'
\fIaltdir\fR
.RE
.RS 4
\h'-04'\(bu\h'+03'
\fIcurl\-opt\fR
.RE
.RS 4
\h'-04'\(bu\h'+03'
\fImirror\fR
(kept unique per version only)
.RE
.SH "AUTHOR"
Written by Minto van der Sluis (misl).
.sp
.SH "REPORTING BUGS"
Report bugs to <list@opensde.org>.
.sp
.SH "COPYRIGHT"
Copyright \(co 2007 The OpenSDE project. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.sp
