.\"     Title: sde-commit
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 01/26/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "SDE\-COMMIT" "1" "01/26/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sde\-commit \- Commit changes
.SH "SYNOPSIS"
\fBsde commit\fR [\fIDISCRIMINATOR\fR] [\fIOPTIONS\fR] [\fIITEMS\fR]
.sp
.SH "DESCRIPTION"
Commits changes to the identified part (item) within the sde environment section indicated by the discriminator. When the user has commit rights to the SCM repository containing the item, using this command will indeed commit the changes. If there are no commit rights to the repository, all changes will be wrapped up in a patch and send to the mailing list.
.sp
.SH "DISCRIMINATORS"
.PP
\fBpackage, pkg\fR
.RS 4
Commits changes to the specified packages (items).
.RE
.PP
\fBrepository, repo\fR
.RS 4
Commits all modified pkgs in the specified repositories (items).
.RE
.PP
\fBsystem, sys\fR
.RS 4
Commits all changes to the sde framework itself. For this discriminator no items should be provided.
.RE
.PP
\fBtarget, tgt\fR
.RS 4
Commits all changes to the specified targets (items).
.RE
When no discriminator is specified, this command will default to the closest discriminator in regard to the current working directory.
.sp
.SH "OPTIONS"
.PP
\fB\-d, \-\-dry\-run\fR
.RS 4
Gives feedback of what would be done, but does not really commit.
.RE
.PP
\fB\-m, \-\-message\fR
.RS 4
Allows to specify the commit message on the command line. The argument specifies the actual commit message.
.RE
.PP
\fB\-f, \-\-file\fR
.RS 4
Allows long commit messages to be read from file. The argument specifies the file from which to read the message.
.RE
.PP
\fB\-q, \-\-quiet\fR
.RS 4
Reduces the verbosity level.
.RE
.PP
\fB\-v, \-\-verbose\fR
.RS 4
Increases the verbosity level.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.nf
sde ci .
.fi
.RE
.SH "AUTHOR"
Written by Minto van der Sluis (misl).
.sp
.SH "REPORTING BUGS"
Report bugs to <list@opensde.org>.
.sp
.SH "COPYRIGHT"
Copyright \(co 2007 The OpenSDE project. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.sp
