.\"     Title: sde-import
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 07/10/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "SDE\-IMPORT" "1" "07/10/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sde\-import \- import stuff into the system
.SH "SYNOPSIS"
\fIsde import\fR [OPTIONS]
.sp
.SH "DESCRIPTION"
Imports the specified filename into the opensde environment under the name specified by item. If no item name is specified the original, as it was exported, item name will be used. The content of the specified file need to match the kind of content specified by the discriminator. In case the content does not match the command will abort with an error message.
.sp
