.\"     Title: sde-list
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 07/12/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "SDE\-LIST" "1" "07/12/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sde\-list \- produce lists needed by other commands
.SH "SYNOPSIS"
\fIsde list\fR [DISCRIMINATOR] [OPTIONS] [ITEMS\]
.sp
.SH "DISCRIMINATORS"
.PP
package, pkg
.RS 4
packages
.RE
.PP
download
.RS 4
downloadable files of a list of packages, or all if no package is given
.RE
.SH "OPTIONS FOR PACKAGES"
.PP
\-a, \-\-arch
.RS 4
list the packages available for the specified architecture, ignoring the given items and other options.
.RE
.PP
\-c, \-\-cfg
.RS 4
use an specified config to see the active packages, instead of all of them.
.RE
.PP
\-r, \-\-repositories
.RS 4
the given list is a list of repositories, not packages.
.RE
.PP
\-e, \-\-extenders
.RS 4
include the packages which extend the given items.
.RE
.SH "OPTIONS FOR DOWNLOAD"
.PP
\-c, \-\-cfg
.RS 4
list the download files needed for a given config.
.RE
.PP
\-r, \-\-repositories
.RS 4
the given list is a list of repositories, not packages.
.RE
.PP
\-e, \-\-extenders
.RS 4
include the download files of the active extenders on the specified config.
.RE
.PP
\-k, \-\-checksum
.RS 4
include the checksum value when listing.
.RE
.PP
\-l, \-\-location
.RS 4
include the download location when listing.
.RE
