.\"     Title: sde-install
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 11/26/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "SDE\-INSTALL" "1" "11/26/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sde\-install \- Takes care of installing software on you host system.
.SH "SYNOPSIS"
\fBsde install\fR
.sp
.SH "DESCRIPTION"
Install the \fBsde\fR wrapper on \fB$HOME/bin\fR which is expected to be on your \fB$PATH\fR. The \fBsde\fR wrapper is only copied if the current version is newer than an existing one.
.sp
.SH "AUTHOR"
Written by Minto van der Sluis (misl).
.sp
.SH "REPORTING BUGS"
Report bugs to <list@opensde.org>.
.sp
.SH "COPYRIGHT"
Copyright \(co 2007 The OpenSDE project. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.sp
