.\"     Title: sde-create
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 07/10/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "SDE\-CREATE" "1" "07/10/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sde\-create \- enhance the system with new parts
.SH "SYNOPSIS"
\fIsde create\fR [OPTIONS]
.sp
.SH "DESCRIPTION"
Create a new part with the identified name (item) within the sde environment section indicated by the discriminator.
.sp
