.\"     Title: sde-cleanup
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 07/10/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "SDE\-CLEANUP" "1" "07/10/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sde\-cleanup \- cleanup part of the system
.SH "SYNOPSIS"
\fIsde cleanup\fR [OPTIONS]
.sp
.SH "DESCRIPTION"
Cleans up the identified part (item) of the \fIsde\fR indicated by the discriminator. If no item is specified the whole section (discriminator) in the \fIsde\fR environment is cleaned up. Depending on the specified item or discriminator, cleanup indicates tidying things up or removing it completely
.sp
