.\"     Title: sde
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 07/10/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "SDE" "1" "07/10/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sde \- front end wrapper
.SH "SYNOPSIS"
\fIsde\fR [COMMAND] [DISCRIMINATOR] [OPTIONS]
.sp
.SH "DESCRIPTION"
The sde frontend wrapper is supposed to help to use the \fIsde\fR commands from within multiple \fIsde\fR trees, from \fI$PATH\fR
.sp
