.\"     Title: sde
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: 01/26/2008
.\"    Manual: 
.\"    Source: 
.\"
.TH "SDE" "1" "01/26/2008" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
sde \- front end wrapper
.SH "SYNOPSIS"
\fBsde\fR [\fICOMMAND\fR] [\fIDISCRIMINATOR\fR] [\fIOPTIONS\fR] [\fIITEMS\fR]
.sp
.SH "DESCRIPTION"
The \fBsde\fR frontend wrapper is a single command to access all OpenSDE functionality. It is a wrapper since it wraps all existing commands in a single interface. Beyond this simple wrapping the command makes it also possible to work with separate sde environments. For this the environment variable \fBSDEROOT\fR is used.
.sp
.SH "COMMANDS"
Various commands are available, each one targeting a special operation. Amongst these commands are:
.sp
.sp
.RS 4
.nf
build    \- building packages
clean    \- cleaning part of your environment
config   \- configuring part of your environment
create   \- creating new packages or target
download \- downloading packages
install  \- installing sde or packages on your current system
update   \- updating packages
.fi
.RE
For a complete list of commands execute the following command: sde help
.sp
.SH "DISCRIMINATORS"
OpenSDE supports various discriminators, however what discriminators are valid depends on the command being used.
.sp
.SH "OPTIONS"
Many different options are valid. However what options are valid depends on the command in combination with the discriminator being used.
.sp
.SH "ENVIRONMENT"
.PP
\fBSDEROOT\fR
.RS 4
When
\fBSDEROOT\fR
is set, sde uses it as the path to your sde environment. If not specified the current working directory is used.
.RE
.SH "AUTHOR"
Written by Minto van der Sluis (misl).
.sp
.SH "REPORTING BUGS"
Report bugs to <list@opensde.org>.
.sp
.SH "COPYRIGHT"
Copyright \(co 2007 The OpenSDE project. This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.sp
