#!/bin/sh
# --- SDE-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
#
# Filename: lib/sde-download/dump-tokenized.sh
# Copyright (C) 2009 The OpenSDE Project
#
# More information can be found in the files COPYING and README.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- SDE-COPYRIGHT-NOTE-END ---

# returns mutilated but grep friendly content of a page
#
# (It will include many empty lines, but it doesn't worth to remove them
# here)
#

exec "${0%/*}/dump.sh" "$@" | sed -e "s,[\r\t\"'<>= /],\n,g"
