# --- SDE-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
#
# Filename: lib/sde-commit/commit-message.awk
# Copyright (C) 2006 - 2008 The OpenSDE Project
# Copyright (C) 2004 - 2006 The T2 SDE Project
#
# More information can be found in the files COPYING and README.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- SDE-COPYRIGHT-NOTE-END ---

BEGIN { FS="[ /]" }

/^\+\+\+ / { pkg = $4 }
{ if (sub(/^\+\[I\] /,"") ) { title = $0 } }

/^\-\[V\] / { oldver=$2 }
/^\+\[V\] / {
	newver=$2
	if ( oldver )
		print pkg ": Updated (" oldver " -> " newver ")"
	else {
		print pkg ": Added " pkg " " newver " - " title
	}
	oldver="" ; newver="" ; info=""
}
